import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { db } from "../db/client.js";
import { toEtDate, toEtTimestamp } from "../lib/time.js";

export type ClientRef = {
  id: number;
  short_name: string;
  display_name: string;
};

type Snapshot = {
  id: number;
  client_id: number;
  captured_at: string;
};

type AccountMetrics = {
  followers_count: number;
  follows_count: number;
  media_count: number;
  reach: number;
  profile_views: number;
  website_clicks: number | null;
};

type PostMetric = {
  ig_media_id: string;
  media_type: string;
  caption: string | null;
  permalink: string;
  published_at: string;
  like_count: number;
  comments_count: number;
  reach: number | null;
  saved: number | null;
  shares: number | null;
  video_views: number | null;
};

const REPORTS_DIR = resolve("reports");

// How many of the most recent snapshots are rendered in the rolling report.
// Older snapshots fall through to the archive file. ~3 months of weekly runs.
const ROLLING_WINDOW = 12;

export type GenerateReportResult = {
  rollingPath: string;
  archivePath: string | null;
};

export function generateReport(client: ClientRef): GenerateReportResult {
  const snapshots = db
    .prepare(
      `SELECT id, client_id, captured_at
         FROM snapshots
         WHERE client_id = ?
         ORDER BY id DESC`,
    )
    .all(client.id) as Snapshot[];

  const rollingSnapshots = snapshots.slice(0, ROLLING_WINDOW);
  const archiveSnapshots = snapshots.slice(ROLLING_WINDOW);

  // Each section compares its snapshot to the next-older one. For the oldest
  // snapshot in the *whole history*, there is no prior — show "—". For the
  // oldest in the rolling window but not in history, we still have a prior
  // available (it lives in `archiveSnapshots[0]`).
  const sectionsRolling = rollingSnapshots.map((snap, i) => {
    const prior =
      rollingSnapshots[i + 1] ?? archiveSnapshots[0] ?? undefined;
    return renderSnapshotSection(snap, prior);
  });
  const sectionsArchive = archiveSnapshots.map((snap, i) => {
    const prior = archiveSnapshots[i + 1] ?? undefined;
    return renderSnapshotSection(snap, prior);
  });

  mkdirSync(REPORTS_DIR, { recursive: true });

  const rollingPath = resolve(REPORTS_DIR, `${client.short_name}.md`);
  writeFileSync(
    rollingPath,
    renderRolling(client, sectionsRolling, archiveSnapshots.length),
    "utf-8",
  );

  let archivePath: string | null = null;
  if (archiveSnapshots.length > 0) {
    archivePath = resolve(REPORTS_DIR, `${client.short_name}_archive.md`);
    writeFileSync(archivePath, renderArchive(client, sectionsArchive), "utf-8");
  }

  return { rollingPath, archivePath };
}

function renderRolling(
  client: ClientRef,
  sections: string[],
  archivedCount: number,
): string {
  const lines: string[] = [];
  lines.push(`# AnalyticsAudit — ${client.display_name}`);
  lines.push("");
  if (sections.length === 0) {
    lines.push("*No snapshots yet — run `npm run audit` to capture one.*");
    lines.push("");
  } else {
    const tail =
      archivedCount > 0
        ? ` Older entries (${archivedCount}) archived in \`${client.short_name}_archive.md\`.`
        : "";
    lines.push(
      `*Rolling report — last ${sections.length} of the most recent ${ROLLING_WINDOW} snapshot(s).${tail}*`,
    );
    lines.push("");
    lines.push(sections.join("\n"));
  }
  lines.push("---");
  lines.push("*Generated by AnalyticsAudit v0.1.0*");
  lines.push("");
  return lines.join("\n");
}

function renderArchive(client: ClientRef, sections: string[]): string {
  const lines: string[] = [];
  lines.push(`# AnalyticsAudit — ${client.display_name} (archive)`);
  lines.push("");
  lines.push(
    `*Snapshots older than the most recent ${ROLLING_WINDOW}. See \`${client.short_name}.md\` for current.*`,
  );
  lines.push("");
  lines.push(sections.join("\n"));
  lines.push("---");
  lines.push("*Generated by AnalyticsAudit v0.1.0*");
  lines.push("");
  return lines.join("\n");
}

function renderSnapshotSection(
  snapshot: Snapshot,
  prior: Snapshot | undefined,
): string {
  const accountMetrics = db
    .prepare(
      `SELECT followers_count, follows_count, media_count,
              reach, profile_views, website_clicks
         FROM account_metrics WHERE snapshot_id = ?`,
    )
    .get(snapshot.id) as AccountMetrics;

  const priorAccountMetrics = prior
    ? (db
        .prepare(
          `SELECT followers_count, follows_count, media_count,
                  reach, profile_views, website_clicks
             FROM account_metrics WHERE snapshot_id = ?`,
        )
        .get(prior.id) as AccountMetrics | undefined)
    : undefined;

  const posts = db
    .prepare(
      `SELECT ig_media_id, media_type, caption, permalink, published_at,
              like_count, comments_count, reach, saved, shares, video_views
         FROM post_metrics
         WHERE snapshot_id = ?
         ORDER BY published_at DESC`,
    )
    .all(snapshot.id) as PostMetric[];

  const priorPostCount = prior
    ? (
        db
          .prepare("SELECT COUNT(*) AS c FROM post_metrics WHERE snapshot_id = ?")
          .get(prior.id) as { c: number }
      ).c
    : 0;

  const lines: string[] = [];

  lines.push(
    `## ${toEtDate(snapshot.captured_at)} — snapshot #${snapshot.id}`,
  );
  lines.push("");
  lines.push(`- **Captured:** ${toEtTimestamp(snapshot.captured_at)}`);
  if (prior) {
    const elapsed = formatElapsed(prior.captured_at, snapshot.captured_at);
    lines.push(
      `- **Prior:** #${prior.id} captured ${toEtTimestamp(prior.captured_at)} (${elapsed} earlier)`,
    );
  } else {
    lines.push("- **Prior:** (none — first snapshot for this client)");
  }
  lines.push("");

  lines.push("### Account");
  lines.push("");
  lines.push("| Metric             | Current | Prior    | Change      |");
  lines.push("|--------------------|--------:|---------:|-------------|");
  const accountRows: Array<[string, number, number | undefined]> = [
    [
      "Followers",
      accountMetrics.followers_count,
      priorAccountMetrics?.followers_count,
    ],
    [
      "Following",
      accountMetrics.follows_count,
      priorAccountMetrics?.follows_count,
    ],
    [
      "Total media",
      accountMetrics.media_count,
      priorAccountMetrics?.media_count,
    ],
    ["Reach (7d)", accountMetrics.reach, priorAccountMetrics?.reach],
    [
      "Profile views (7d)",
      accountMetrics.profile_views,
      priorAccountMetrics?.profile_views,
    ],
  ];
  for (const [label, current, previous] of accountRows) {
    const cur = formatNumber(current).padStart(7);
    const prev = (previous !== undefined ? formatNumber(previous) : "—").padStart(8);
    const change = formatDelta(current, previous).padEnd(11);
    lines.push(`| ${label.padEnd(18)} | ${cur} | ${prev} | ${change} |`);
  }
  lines.push("");

  lines.push("### Posts");
  lines.push("");
  const noInsights = posts.filter((p) => p.reach === null).length;
  lines.push(`- This snapshot: ${posts.length} post(s)`);
  lines.push(
    prior
      ? `- Prior snapshot (#${prior.id}): ${priorPostCount} post(s)`
      : "- Prior snapshot: —",
  );
  if (noInsights > 0) {
    lines.push(
      `- ${noInsights} post(s) returned no insights (likely pre-business-conversion media)`,
    );
  }
  lines.push("");

  if (posts.length > 0) {
    lines.push(
      "| Posted     | Type            | Likes | Comments | Reach | Saved | Shares | Views | Permalink |",
    );
    lines.push(
      "|------------|-----------------|------:|---------:|------:|------:|-------:|------:|-----------|",
    );
    for (const p of posts) {
      const posted = toEtDate(p.published_at);
      const cells = [
        posted,
        p.media_type.padEnd(15),
        formatNumber(p.like_count).padStart(5),
        formatNumber(p.comments_count).padStart(8),
        formatNullable(p.reach).padStart(5),
        formatNullable(p.saved).padStart(5),
        formatNullable(p.shares).padStart(6),
        formatNullable(p.video_views).padStart(5),
        `[view](${p.permalink})`,
      ];
      lines.push(`| ${cells.join(" | ")} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function formatNumber(n: number): string {
  return n.toLocaleString("en-US");
}

function formatNullable(n: number | null): string {
  return n === null ? "—" : formatNumber(n);
}

// `—` means "no comparable signal" — either there's no prior value, the
// prior value was zero (division would be undefined), or nothing changed.
function formatDelta(current: number, previous: number | undefined): string {
  if (previous === undefined) return "—";
  const delta = current - previous;
  if (delta === 0) return "0 (—)";
  const sign = delta > 0 ? "+" : "";
  if (previous === 0) return `${sign}${formatNumber(delta)} (—)`;
  const pct = (delta / previous) * 100;
  const pctSign = pct >= 0 ? "+" : "";
  return `${sign}${formatNumber(delta)} (${pctSign}${pct.toFixed(1)}%)`;
}

function formatElapsed(fromIso: string, toIso: string): string {
  const ms = new Date(toIso).getTime() - new Date(fromIso).getTime();
  const minutes = Math.floor(ms / 60000);
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hr`;
  const days = Math.floor(hours / 24);
  return `${days} day(s)`;
}
